#!/usr/bin/env bash
source /dev/stdin < <(cli loader)
cli::import cli initialize
cli::import cli export

help() {
    cat << EOF
Command
    cli_constant

Global Arguments
    --help -h               : Show this message and exit.
    --self-test             : Run a self test.
EOF
}

main() {
    CONSTANT_PI='3.14159'

    cli::export constant
}

self_test() { 
    source /dev/stdin < <(main)
    source /dev/stdin < <(cli::import cli_assert)

    assert::eq ${CONSTANT_PI} '3.14159'
}

cli::load "$@"