#!/usr/bin/env bash
source $(cli loader)

help() {
    cat << EOF
Command
    ${CLI_COMMAND}

Global Arguments
    --help -h               : Show this message and exit.
    --self-test             : Run a self test.
EOF
}

export() {
    CONSTANT_PI='3.141592'

    cli::export constant
}

self_test() { 
    source /dev/stdin < <(main)
    source /dev/stdin < <(cli::import cli_assert)

    assert::eq ${CONSTANT_PI} '3.141592'
}

cli::main "$@"